// 'use strict';

// const createBooking = function ( flightNum, numPassenger, price ) {
//     flightNum = 'A37',
//     numPassenger = 10
// }

// const greet = function(greeting) {
//     return function(name) {
//         console.log(`${greeting}, ${name}.`);
//     }
// }

// const greeterFunction = greet('Hello');
// greeterFunction('Sohan')

// // console.log(greet('Hi')('Sudeb')); returns undefined.

// greet('Hi')('Sudeb');

// function sayHello (name) {
//     console.log(`Hello ${name}`);
// }

// sayHello('sudeb');

// // Closures
// const secureBooking = function () {
//     let passengerCount = 0;

//     return function () {
//         passengerCount++;
//         console.log(`{passengerCount} passengers`);
//     } 
// }

// const booker = secureBooking();

/*
Questions generated by Chat GPT for Functions:

*Prompt: Give me question on Functions and it's methods to practise of various levels of difficulties and estimated time to solve them.

---> Easy Level

Question: Write a function add(a, b) that takes two numbers as arguments and returns their sum.
Estimated Time: 5 minutes

Question: Create a function isEven(num) that returns true if the number is even and false if it is odd.
Estimated Time: 5 minutes   

Question: Write a function greet(name) that returns a greeting message, e.g., "Hello, [name]!".
Estimated Time: 5 minutes    

---> Medium Level

Question: Write a function factorial(n) that returns the factorial of a given non-negative integer n. Use recursion.
Estimated Time: 10 minutes 

Question: Create a function fibonacci(n) that returns the nth Fibonacci number. Implement it using both iterative and recursive methods.
Estimated Time: 15 minutes 

Question: Write a function reverseString(str) that takes a string as input and returns the string reversed.
Estimated Time: 10 minutes    

---> Hard Level

Question: Implement a function debounce(func, delay) that creates a debounced version of the provided function. The debounced function should delay the invocation of func until after delay milliseconds have elapsed since the last time it was invoked.
Estimated Time: 20 minutes   

Question: Write a function throttle(func, limit) that creates a throttled version of the provided function. The throttled function should only be able to execute once every limit milliseconds.
Estimated Time: 20 minutes

Question: Create a function mergeSort(arr) that sorts an array using the merge sort algorithm. Return the sorted array.
Estimated Time: 25 minutes    

---> Expert Level

Question: Write a function memoize(fn) that takes a function fn as an argument and returns a memoized version of that function. The memoized function should cache results for previously computed inputs.
Estimated Time: 30 minutes    

Question: Implement a function compose(...funcs) that takes a variable number of functions as arguments and returns a new function that is the composition of those functions.
Estimated Time: 25 minutes    

Question: Create a function currying(fn) that transforms a function fn into a curried version of itself. The curried function should allow partial application of its arguments.
Estimated Time: 30 minutes  
*/

function add(a, b) {
    if(typeof a === 'number' && typeof b === 'number') return a+b;
    throw new Error('Invalid Inputs: Both arguments should be a number');
}

function isEven(num) {
    if(typeof num === 'number') return num % 2 === 0;
    throw new Error('Invalid Inputs: argument should be a number');
}

function greet(name) {
    if(typeof name === 'string') return `Hello, ${name}!`;
    throw new Error('Invalid Inputs: argument should be a string');
}

function getFactorial(num)  {
    if(typeof num === 'number' && num > 0) {
        function factorial(num) {
            if(num > 1) return num*factorial(num-1);
            return num
        }
        return factorial(num);
    };
    throw new Error('Invalid Inputs: argument should be a number or greater than 0');
}

function fibonacci(n, logic = '') {
    if(typeof n === 'number' && n >= 0 && (logic === 'iterative' || logic === 'recursive')) {
        const res = [0,1];
        const methods = {
            'iterative': (upto) => {
                for(let i = 0; i < upto-2; i++) {
                    res.push(res[length-2] + res[length-1]);
                }
            },
            'recursive': (upto) => {
                if(res.length < upto ) methods.recursive();
                res.push(res[length-2] + res[length-1]);
            }
        }

        if(res.length >= n) {
            return res[n+1]
        }
        return methods[logic](num);
    };
    throw new Error('Invalid Inputs: argument should be a number or greater than 0');
}

function commonFnHandler(fn, ...args) {
    try {
        console.log(fn(...args));
    } catch (error) {
        console.error(error.message); // Outputs Error Statement
    }
}

commonFnHandler(add,2,3);
commonFnHandler(add,'a','b');

commonFnHandler(isEven, 2);
commonFnHandler(isEven, 3);
commonFnHandler(isEven,'a');

commonFnHandler(greet, 'World');
commonFnHandler(greet, 2);

commonFnHandler(getFactorial, 0);
commonFnHandler(getFactorial, 1);
commonFnHandler(getFactorial, 5);
commonFnHandler(getFactorial, -5);

commonFnHandler(fibonacci, 5, 'iterative');
commonFnHandler(fibonacci, 5, 'recursive');

commonFnHandler(fibonacci, 0, 'iterative');
commonFnHandler(fibonacci, 0, 'recursive');
